import type { Content, Layer } from './content-schema'
export type { Content, Project, Tool, Experience, Layer, Media, Detail } from './content-schema'

// All copy and data for the site — values agreed with Viraj in content/decisions.md (2026-09-12).
// Plain data only (no zod at runtime) so client components can import it cheaply; tests/content.test.ts validates it.
const GH = 'https://github.com/virajdomadia'
const LI = 'https://www.linkedin.com/in/viraj-domadia-6b89751b5'

export const content: Content = {
  person: {
    name: 'Viraj Domadia', first: 'Viraj', last: 'Domadia',
    role: 'Frontend-heavy full-stack developer', roleShort: 'Full-stack developer', jobTitle: 'Software Engineer',
    city: 'Bengaluru', region: 'Karnataka', country: 'India', countryCode: 'IN', origin: 'Mumbai', tz: 'IST (UTC+5:30)',
    email: 'virajdomadia6@gmail.com', phone: '+918828091294', phoneDisplay: '+91 88280 91294',
    github: GH, linkedin: LI, resume: '/Viraj-Domadia-Resume.pdf', available: 'Available · 2026',
    languages: ['English', 'Hindi', 'Gujarati'],
    bio: 'Viraj Domadia is a frontend-heavy full-stack developer based in Bengaluru, originally from Mumbai. He works with React, Next.js, TypeScript, Node.js, Express, FastAPI, PostgreSQL and MongoDB. He builds the client, the server and the data layer as one product, and has six full-stack products live, from Tripsmith to Platter. He is completing an online MCA at Amity University (2025–2027) and is open to full-time and freelance work, on-site in Bengaluru or remote.',
    employer: { name: 'Zapigo', url: 'https://zapigo.com' },
  },
  hero: {
    eyebrow: ['Frontend-heavy full-stack developer', 'Bengaluru, IN', 'Open to full-time & freelance'],
    lede: 'I build the client, the server and the data layer — React, Next.js, Node, Postgres and Mongo — and ship them as products. Six are live below.',
    corners: ['Viraj Domadia', 'Bengaluru · IST', 'React · Next · Node', 'Building since 2024'],
    stats: [{ n: '2+', label: 'years building' }, { n: '6', label: 'products live' }, { n: '30', label: 'tools in the stack' }],
    bgAlt: 'Illustration of a developer at a desk with three monitors',
  },
  marquee: {
    stack: ['React', 'Next.js', 'TypeScript', 'Node', 'Express', 'FastAPI', 'PostgreSQL', 'MongoDB', 'Tailwind'],
    b: ['Six products live', 'Code on GitHub', 'Bengaluru · IST', 'Open to full-time & freelance', 'Frontend-heavy full-stack'],
  },
  about: {
    quote: 'I build the client, the server and the data layer as one product. I like code a reviewer can read in one sitting.',
    quoteBold: ['one product', 'one sitting'],
    photoAlt: 'Illustration of a developer planning a web project at a whiteboard',
    captions: ['Bengaluru · IST', 'Open to work'],
    counters: [{ to: 2, suffix: '+', label: 'years building' }, { to: 6, suffix: '', label: 'products live' }, { to: 30, suffix: '', label: 'tools in the stack' }],
    rail: 'About — Viraj Domadia — Bengaluru — 2026 —',
  },
  experience: [
    { year: '2025', period: '→ now', title: 'Software Engineer · Zapigo', org: 'Zapigo', orgUrl: 'https://zapigo.com', start: '2025-10', end: null,
      desc: 'Own the frontend of zapigo.com: Next.js 16, React 19, TypeScript, Tailwind v4, TanStack Query, Zustand and React Aria, with Vitest + Playwright tests and Sentry monitoring. Built Personal Invites end to end — create and share a digital invitation in under 30 seconds — including its FastAPI + PostgreSQL backend.',
      chips: ['Next.js 16', 'TypeScript', 'Tailwind v4', 'TanStack Query', 'FastAPI', 'PostgreSQL'], kind: 'job' },
    { year: '2024', period: '– 2025', title: 'IT Executive · Venus Vacations Pvt. Ltd', org: 'Venus Vacations Pvt. Ltd', start: '2024-07', end: '2025-11',
      desc: 'Ran the company’s IT and hardware. Alongside that, built the company website with a custom booking engine end to end — React front, Node/Express API, MongoDB — taken through internal review, not deployed.',
      chips: ['React', 'Node · Express', 'MongoDB'], kind: 'job' },
    { year: '2022', period: '– 2023', title: 'Application Development Associate · Accenture', org: 'Accenture', orgUrl: 'https://www.accenture.com', start: '2022-12', end: '2023-07',
      desc: 'Backup and support engineer on an enterprise client account: monitored NetBackup jobs, handled incidents and restores, and worked to SLAs in a large operations team.',
      chips: ['NetBackup', 'Incident support', 'Enterprise IT'], kind: 'job' },
  ],
  education: [
    { degree: 'Master of Computer Applications (online)', school: 'Amity University', schoolUrl: 'https://www.amity.edu', years: '2025–2027' },
    { degree: 'B.Sc. Information Technology', school: 'Narsee Monjee College of Commerce and Economics, Mumbai University', years: '2019–2022', note: '8.33 CGPA' },
  ],
  projects: [
    { slug: 'tripsmith', title: 'Tripsmith', category: 'Travel + AI concierge', status: 'v2 live · bookings + payments',
      blurb: 'A travel agency on its own site: book and pay by Razorpay (test mode) with live seats, deals and coupons, get a PDF voucher, manage trips and reviews in an account; an owner desk runs the bookings. AI concierge next.',
      stack: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Tailwind CSS', 'Razorpay'],
      live: 'https://tripsmith.virajdomadia.com', repo: 'https://github.com/virajdomadia/tripsmith', image: '/images/projects/tripsmith.jpg',
      detail: {
        pitch: 'A travel agency’s own booking site: live seats, Razorpay checkout, PDF vouchers and GST invoices, and an owner desk on the same API.',
        facts: { role: 'Solo — design, frontend, API, database, deploy', year: '2026', version: 'v2.5 (in progress)' },
        media: [
          { kind: 'image', src: '/projects/tripsmith/home.webp', alt: 'Tripsmith home page: headline over a Kerala backwaters photo and a search by place, month and budget', caption: 'Home — search by place, month and budget' },
          { kind: 'clip', webm: '/projects/tripsmith/browse.webm', mp4: '/projects/tripsmith/browse.mp4', poster: '/projects/tripsmith/browse.jpg', seconds: 8, alt: 'Clip: searching Himachal from the home page and opening the Kasol package', caption: 'Search to package' },
          { kind: 'image', src: '/projects/tripsmith/package.webp', alt: 'Leh · Nubra · Pangong package page with its photo gallery', caption: 'A package page — real itinerary, hotels and photos' },
          { kind: 'image', src: '/projects/tripsmith/sheet.webp', alt: 'Booking sheet: departure dates with live seat counts and the price summary', caption: 'Book now — live seats, price summary, pay in full or 25% deposit' },
          { kind: 'clip', webm: '/projects/tripsmith/book.webm', mp4: '/projects/tripsmith/book.mp4', poster: '/projects/tripsmith/book.jpg', seconds: 10, alt: 'Clip: picking a date, adding rafting and applying a coupon while the total updates', caption: 'Live seats and a server quote' },
          { kind: 'image', src: '/projects/tripsmith/sheet-extras.webp', alt: 'Booking sheet showing a rafting add-on and a coupon in the price breakdown', caption: 'Add-ons and a coupon, priced by the server' },
          { kind: 'clip', webm: '/projects/tripsmith/pay.webm', mp4: '/projects/tripsmith/pay.mp4', poster: '/projects/tripsmith/pay.jpg', seconds: 12, alt: 'Clip: paying in Razorpay test mode with a test card and OTP until the payment succeeds', caption: 'Razorpay test-mode checkout — card, OTP, paid' },
          { kind: 'image', src: '/projects/tripsmith/my-trips.webp', alt: 'My trips page listing upcoming and past bookings', caption: 'My trips — bookings, balances, reviews' },
          { kind: 'image', src: '/projects/tripsmith/trip.webp', alt: 'One booking with its voucher, GST documents and activity log', caption: 'A booking — voucher, invoice, activity' },
          { kind: 'image', src: '/projects/tripsmith/desk.webp', alt: 'Owner dashboard with money in, upcoming departures and open enquiries', caption: 'Owner desk — the Money desk dashboard' },
          { kind: 'clip', webm: '/projects/tripsmith/counter.webm', mp4: '/projects/tripsmith/counter.mp4', poster: '/projects/tripsmith/counter.jpg', seconds: 10, alt: 'Clip: the owner building a counter booking with a manual discount and a live quote', caption: 'Owner counter booking' },
          { kind: 'image', src: '/projects/tripsmith/desk-booking.webp', alt: 'Owner view of a booking with its lifecycle timeline', caption: 'Owner booking view — the append-only timeline' },
        ],
        sections: {
          problem: 'A small Indian tour agency sells fixed-date group trips: a set itinerary, a price per person and a limited number of seats per departure. Most run on WhatsApp, phone calls and a spreadsheet, so two people can pay for the same last seat, prices are worked out by hand, and nobody can see who changed a booking. Tripsmith is that agency’s own site, built so every seat, rupee and change is accounted for.',
          built: 'A Next.js site with 14 packages and 51 departures; package and destination pages are generated ahead of time and refresh on demand when the owner edits them. A FastAPI + Postgres API behind it. Customers book with live seats, add-ons, deals, early-bird prices and coupons; pay in full or a 25% deposit through Razorpay in test mode; get a PDF voucher and GST invoice; and sign in with an emailed 6-digit code to manage their trips. The owner runs bookings, refunds, enquiries, packages, coupons, reviews and counter bookings over Razorpay Payment Links from an admin desk on the same API.',
          decisions: [
            { title: 'The server owns the price', body: 'Every quote is built on the server in whole paise: deal, then early-bird, then coupon, with add-ons added last. The browser never sends a price; the owner’s counter screen sends the total it expects and gets 409 price_changed if it moved.' },
            { title: 'Seats are held, not hoped for', body: 'Pressing Pay creates a 10-minute hold. The server locks the customer’s email or phone, then the departure row (FOR UPDATE). A test fires two orders for the last seat at once: exactly one wins, the other gets 409 sold_out.' },
            { title: 'All payments go through one capture function', body: 'The Checkout callback, the sync when Checkout closes, the webhook and payment links all lead into it. Signatures are checked with HMAC and a unique Razorpay payment id turns replays into no-ops. A payment that lands after the seats are gone is cancelled and refunded automatically through the Razorpay refund API.' },
            { title: 'History can’t be rewritten', body: 'Every booking change is written to booking_events, and a Postgres trigger refuses any UPDATE or DELETE on it. The owner sees it as a timeline, the customer as “Activity”.' },
            { title: 'GST numbers have no gaps', body: 'Receipts, tax invoices and credit notes are numbered per financial year (TS/2026-27/0001) from a counter row taken in the same transaction as the document; PDFs are made with fpdf2. The GSTIN is a demo one, labelled not registered.' },
          ],
          outcome: 'Live at tripsmith.virajdomadia.com, taking bookings in Razorpay test mode. Over 750 API tests and over 500 web tests. CI runs three jobs: web, api, and an OpenAPI contract check that fails if the generated types drift. The booking page scores 94 on PageSpeed mobile.',
        },
        versions: [
          { name: 'v1 Agency website', summary: 'Catalog, search, package pages, enquiries + WhatsApp, itinerary PDF, owner admin.', state: 'shipped' },
          { name: 'v2 Booking engine', summary: 'Razorpay checkout, webhooks, accounts, deals, coupons, reviews, owner bookings desk.', state: 'shipped' },
          { name: 'v2.5 Strengthen', summary: 'Partly live: history log, refunds + GST documents, add-ons, early-bird, deposit + balance, counter booking, admin redesign. Still to come: waitlist, date change, calendar, reports.', state: 'next' },
          { name: 'v3 AI concierge', summary: 'Chat that searches the catalog, checks seats and starts a booking.', state: 'next' },
          { name: 'v4 Tripsmith anywhere', summary: 'An MCP server with the same tools.', state: 'next' },
        ],
        updated: '2026-10-01',
      } },
    { slug: 'frontrow', title: 'Frontrow', category: 'Live seat-map ticketing', status: 'Live',
      blurb: 'Movie and concert tickets on a live seat map: tap a seat and it is held for ten minutes and greys out for everyone else — Redis holds, transactions, idempotent payments, QR tickets.',
      stack: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Redis', 'WebSockets', 'Razorpay'],
      live: 'https://frontrow-viraj.vercel.app', repo: 'https://github.com/virajdomadia/frontrow', image: '/images/projects/frontrow.jpg' },
    { slug: 'pagecraft', title: 'Pagecraft', category: 'Co-edited website builder', status: 'Live',
      blurb: 'A landing-page editor two people use at the same time — live cursors, conflict-free merges, version history — then one click publishes it to its own subdomain.',
      stack: ['Next.js', 'TypeScript', 'Yjs', 'WebSockets', 'FastAPI', 'PostgreSQL'],
      live: 'https://pagecraft-viraj.vercel.app', repo: 'https://github.com/virajdomadia/pagecraft', image: '/images/projects/pagecraft.jpg' },
    { slug: 'offcut', title: 'Offcut', category: 'D2C store + visual search', status: 'Live',
      blurb: 'A complete streetwear store — variants, inventory that cannot go negative, cart, orders, returns, admin — plus “drop a photo, shop the look” search on image embeddings.',
      stack: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'pgvector', 'Cloudinary', 'Razorpay'],
      live: 'https://offcut-viraj.vercel.app', repo: 'https://github.com/virajdomadia/offcut', image: '/images/projects/offcut.jpg' },
    { slug: 'skillroom', title: 'Skillroom', category: 'Video course platform', status: 'Live',
      blurb: 'Creators upload video courses; students buy or subscribe, resume where they left off, pass quizzes and earn a certificate — streaming, recurring billing, payouts, three-role access.',
      stack: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Mux', 'Razorpay Subscriptions'],
      live: 'https://skillroom-viraj.vercel.app', repo: 'https://github.com/virajdomadia/skillroom', image: '/images/projects/skillroom.jpg' },
    { slug: 'platter', title: 'Platter', category: 'Food delivery + live tracking', status: 'Live',
      blurb: 'Customer, restaurant and rider apps on one order state machine — restaurants within a radius, live rider location on the customer’s map, role-checked transitions.',
      stack: ['Next.js', 'TypeScript', 'FastAPI', 'PostGIS', 'WebSockets', 'MapLibre'],
      live: 'https://platter-viraj.vercel.app', repo: 'https://github.com/virajdomadia/platter', image: '/images/projects/platter.jpg' },
  ],
  projectsNote: { after: 'Every project has a live URL and a public repo — open one, then read the code.', afterCta: 'All repos on GitHub' },
  tools: [
    { key: 'react', name: 'React', layer: 'client', years: 2, brand: '#61DAFB' },
    { key: 'nextdotjs', name: 'Next.js', layer: 'client', years: 2, brand: '#1F1B10' },
    { key: 'typescript', name: 'TypeScript', layer: 'client', years: 1, brand: '#3178C6' },
    { key: 'javascript', name: 'JavaScript', layer: 'client', years: 2, brand: '#F7DF1E' },
    { key: 'tailwindcss', name: 'Tailwind CSS', layer: 'client', years: 2, brand: '#06B6D4' },
    { key: 'html5', name: 'HTML5', layer: 'client', years: 2, brand: '#E34F26' },
    { key: 'css3', name: 'CSS3', layer: 'client', years: 2, brand: '#1572B6' },
    { key: 'reactquery', name: 'TanStack Query', layer: 'client', years: 1, brand: '#FF4154' },
    { key: 'zustand', name: 'Zustand', layer: 'client', years: 1, brand: '#443E38' },
    { key: 'framer', name: 'Framer Motion', layer: 'client', years: 1, brand: '#0055FF' },
    { key: 'nodedotjs', name: 'Node.js', layer: 'server', years: 2, brand: '#5FA04E' },
    { key: 'express', name: 'Express', layer: 'server', years: 2, brand: '#1F1B10' },
    { key: 'fastapi', name: 'FastAPI', layer: 'server', years: 1, brand: '#009688' },
    { key: 'socketdotio', name: 'Socket.io', layer: 'server', years: 1, brand: '#1F1B10' },
    { key: 'jsonwebtokens', name: 'JWT', layer: 'server', years: 2, brand: '#1F1B10' },
    { key: 'mongodb', name: 'MongoDB', layer: 'data', years: 2, brand: '#47A248' },
    { key: 'mongoose', name: 'Mongoose', layer: 'data', years: 2, brand: '#880000' },
    { key: 'postgresql', name: 'PostgreSQL', layer: 'data', years: 1, brand: '#4169E1' },
    { key: 'prisma', name: 'Prisma', layer: 'data', years: 1, brand: '#2D3748' },
    { key: 'firebase', name: 'Firebase', layer: 'data', years: 1, brand: '#DD2C00' },
    { key: 'cloudinary', name: 'Cloudinary', layer: 'data', years: 1, brand: '#3448C5' },
    { key: 'git', name: 'Git', layer: 'tooling', years: 2, brand: '#F05032' },
    { key: 'github', name: 'GitHub', layer: 'tooling', years: 2, brand: '#1F1B10' },
    { key: 'docker', name: 'Docker', layer: 'tooling', years: 1, brand: '#2496ED' },
    { key: 'vercel', name: 'Vercel', layer: 'tooling', years: 2, brand: '#1F1B10' },
    { key: 'postman', name: 'Postman', layer: 'tooling', years: 2, brand: '#FF6C37' },
    { key: 'figma', name: 'Figma', layer: 'tooling', years: 1, brand: '#F24E1E' },
    { key: 'vitest', name: 'Vitest', layer: 'tooling', years: 1, brand: '#00A35C' },
    { key: 'playwright', name: 'Playwright', layer: 'tooling', years: 1, brand: '#2EAD33' },
    { key: 'sentry', name: 'Sentry', layer: 'tooling', years: 1, brand: '#362D59' },
  ],
  stack: { heading: 'What I ship with,', headingBold: 'by layer.', note: 'Real logos, years of real use, grouped by where each tool lives. Hover a pill.' },
  band: { headline: 'Build. Ship. Repeat.', sub: 'Code first, slides never — six products are live above, and every line of their code is on GitHub.', alt: 'Illustration of a developer coding at night with a laptop and two monitors' },
  contact: {
    heading: 'Tell me what', headingBold: 'you’re building.',
    lead: 'A role, a project, a question — a few lines is enough. I reply within a day, usually with questions of my own.',
    intents: [{ value: 'role', label: 'Hiring for a role' }, { value: 'project', label: 'A freelance project' }, { value: 'hi', label: 'Just saying hi' }],
    practical: ['Bengaluru, India · IST (UTC+5:30)', 'Open to full-time, freelance, remote', 'Replies within 24h'],
    sentTitle: 'Sent.', sentBody: 'Thanks — I’ll get back to you within a day. Meanwhile, my code is on GitHub.',
  },
  faq: [
    { q: 'Is Viraj Domadia available for work?', a: 'Yes — open to full-time roles and freelance projects, in Bengaluru or remote. Replies within a day.' },
    { q: 'What does Viraj build with?', a: 'React and Next.js with TypeScript on the client; Node/Express and FastAPI APIs; PostgreSQL and MongoDB.' },
    { q: 'Where is Viraj based?', a: 'Bengaluru, India (IST, UTC+5:30); originally from Mumbai. Works with remote teams across time zones.' },
    { q: 'How do I contact Viraj?', a: 'The form on this page, email virajdomadia6@gmail.com, or call +91 88280 91294.' },
  ],
  seo: {
    siteName: 'Viraj Domadia',
    title: 'Viraj Domadia — Frontend-heavy full-stack developer, Bengaluru',
    description: 'Frontend-heavy full-stack developer in Bengaluru — React, Next.js, TypeScript, Node, FastAPI, Postgres, MongoDB. Open to work.',
    keywords: ['Viraj Domadia', 'frontend heavy full stack developer', 'full stack developer Bengaluru', 'react developer Bengaluru', 'Next.js developer Bangalore', 'full stack developer Mumbai', 'MERN developer India', 'freelance web developer Bengaluru'],
    sameAs: [GH, LI],
  },
  footer: { tech: 'Next.js · Tailwind · TypeScript' },
}

export const LAYERS: { key: Layer; label: string }[] = [
  { key: 'client', label: 'Client' }, { key: 'server', label: 'Server' }, { key: 'data', label: 'Data' }, { key: 'tooling', label: 'Tooling' },
]
