import fs from 'node:fs'
const src = JSON.parse(fs.readFileSync(new URL('../../mockups/icons/icons.json', import.meta.url), 'utf8'))
const entries = Object.entries(src).map(([k, v]) => `  ${JSON.stringify(k)}: { d: ${JSON.stringify(v.d)}, title: ${JSON.stringify(v.t)} },`).join('\n')
fs.mkdirSync('components/icons', { recursive: true })
fs.writeFileSync('components/icons/index.tsx', `// generated by scripts/gen-icons.mjs from mockups/icons/icons.json (Simple Icons, CC0) — do not edit\nexport const ICONS: Record<string, { d: string; title: string }> = {\n${entries}\n}\nexport function Icon({ name, className }: { name: string; className?: string }) {\n  const i = ICONS[name]; if (!i) return null\n  return <svg viewBox="0 0 24 24" aria-hidden="true" className={className}><path d={i.d} /></svg>\n}\n`)
console.log('wrote', Object.keys(src).length, 'icons')
