// Builds components/icons/index.tsx: Simple Icons paths for every tool key in lib/content.ts, custom marks where SI has none.
import fs from 'node:fs'
import * as si from 'simple-icons'

const src = fs.readFileSync(new URL('../lib/content.ts', import.meta.url), 'utf8')
const toolsBlock = src.slice(src.indexOf('tools: ['), src.indexOf('],', src.indexOf('tools: [')))
const keys = [...toolsBlock.matchAll(/key: '([a-z0-9]+)'/g)].map((m) => m[1])
const custom = JSON.parse(fs.readFileSync(new URL('./icons-custom.json', import.meta.url), 'utf8'))
// keys renamed upstream (css3 → css): keep the mark the approved mockup used
const legacy = JSON.parse(fs.readFileSync(new URL('../../mockups/icons/icons.json', import.meta.url), 'utf8'))
const out = {}
for (const k of keys) {
  const icon = si['si' + k.charAt(0).toUpperCase() + k.slice(1)]
  if (icon) out[k] = { d: icon.path, t: icon.title }
  else if (custom[k]) out[k] = custom[k]
  else if (legacy[k]) out[k] = legacy[k]
  else throw new Error(`no icon for ${k}`)
}
const entries = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: { d: ${JSON.stringify(v.d)}, title: ${JSON.stringify(v.t)} },`).join('\n')
fs.mkdirSync('components/icons', { recursive: true })
fs.writeFileSync('components/icons/index.tsx', `// generated by scripts/gen-icons.mjs (Simple Icons CC0 + scripts/icons-custom.json) — do not edit\nexport const ICONS: Record<string, { d: string; title: string }> = {\n${entries}\n}\nexport function Icon({ name, className }: { name: string; className?: string }) {\n  const i = ICONS[name]; if (!i) return null\n  return <svg viewBox="0 0 24 24" aria-hidden="true" className={className}><path d={i.d} /></svg>\n}\n`)
console.log('wrote', Object.keys(out).length, 'icons')
